services:
  postgres:
    image: postgres:15 
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: app        
      POSTGRES_PASSWORD: changethis123  
      POSTGRES_DB: app 
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist PostgreSQL data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: 'dracula'
    depends_on:
    - postgres

  backend:
    image: backend:latest
    depends_on: 
    - postgres
    restart: always
    ports:
      - 8000:8000
    env_file: ".env"

  frontend:
    image: frontend:latest
    depends_on: 
    - backend
    - nginx-manager
    restart: always
    # ports:
    #   - 80:80
    environment:
      VITE_API_URL: http://127.0.0.1:8000

  nginx-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

volumes:
  postgres_data:

networks:
  shared-network:
    external: true